apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkpublisher
  labels:
    app: mkpublisher
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mkpublisher
  template:
    metadata:
      labels:
        app: mkpublisher
    spec:
      containers:
      - name: mkpublisher
        image: 872823407497.dkr.ecr.us-east-1.amazonaws.com/mkpublisher:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
